name: Build Cyberdollar Binaries

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  build-linux:
    name: Build Linux Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config \
          libssl-dev libevent-dev bsdmainutils python3 \
          libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev \
          libdb-dev libdb++-dev libzmq3-dev

      - name: Build Source
        run: |
          ./autogen.sh
          ./configure
          mkdir -p build/linux  # Ensure the directory exists for output
          make

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: build/linux

  build-windows:
    name: Build Windows Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-mingw-w64-x86-64

      - name: Configure MinGW
        run: |
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

      - name: Build Source
        run: |
          ./autogen.sh
          ./configure --host=x86_64-w64-mingw32
          mkdir -p build/windows  # Ensure the directory exists for output
          make

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: windows-binaries
          path: build/windows

  build-macos:
    name: Build macOS Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup macOS SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y curl make tar
          curl -O https://bitcoincore.org/depends-sources/sdks/MacOSX10.11.sdk.tar.gz
          mkdir -p depends/SDKs
          tar -C depends/SDKs -xzf MacOSX10.11.sdk.tar.gz

      - name: Build Source
        run: |
          ./autogen.sh
          ./configure --host=x86_64-apple-darwin
          mkdir -p build/macos  # Ensure the directory exists for output
          make

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: macos-binaries
          path: build/macos
